# Generated by Django 4.0.1 on 2022-01-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogusers',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
