# Generated by Django 4.0.1 on 2022-01-08 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagment', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
